// Automatically generated - EDITS WILL BE LOST

// Generated by support/setplatform

#include "platform.h"

const char* dicom3tools_platform_string = "Darwin graythin-1.home 17.7.0 Darwin Kernel Version 17.7.0: Wed May 27 17:00:02 PDT 2020; root:xnu-4570.71.80.1~1/RELEASE_X86_64 x86_64";
